apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    type: db
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: examplepassword
    - name: MYSQL_DATABASE
      value: exampledb
    - name: MYSQL_USER
      value: exampleuser
    - name: MYSQL_PASSWORD
      value: examplepassword
    ports:
    - containerPort: 3306
  - name: mongodb
    image: mongo:3.3
    command: ["mongod"]
    args: ["--rest", "--httpinterface"]
    ports:
    - containerPort: 27017
